inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - "**/*.gemspec"
    - "**/*.rake"
    - "**/config.ru"
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Capfile"
    - "**/Guardfile"
  Exclude:
    - "vendor/**/*"

StringLiterals:
  EnforcedStyle: double_quotes
